name: fpython
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  webview_windows: ^0.4.0
  path_provider: ^2.1.5
  msix: ^3.16.12
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png

msix_config:
  display_name: Molde IDEB
  publisher_display_name: Luis Bezerra
  identity_name: com.example.molde
  msix_version: 1.0.0.0
  logo_path: assets/icons/logo.png
  capabilities: internetClient
